export const SET_LIST_STATE = 'SET_LIST_STATE';
export const RESET_LIST_STATE = 'RESET_LIST_STATE';
export const REMOVE_FROM_LIST_STATE = 'REMOVE_FROM_LIST_STATE';

export const RESET_LIST_CACHE = 'RESET_LIST_CACHE';
export const ADD_TO_LIST_CACHE = 'ADD_TO_LIST_CACHE';
export const REMOVE_FROM_LIST_CACHE = 'REMOVE_FROM_LIST_CACHE';
