import Head from 'next/head';
import { NavBar, Footer } from '../index';
import defaultUserSettings from '../../../attache-defaults.json';

const { name, portfolioTitle } = defaultUserSettings;

export type LayoutProps = {
    children: React.ReactNode;
};

export default function Layout({ children }: LayoutProps): JSX.Element {
    return (
        <>
            <Head>
                <title>{portfolioTitle || `${name}'s Portfolio`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavBar />
            {children}
            <Footer />

        </>
    );
}
