import Head from 'next/head';
import { NavBar, Footer } from '../index';
import defaultUserSettings from '../../../attache-defaults.json';

const { name, portfolioTitle } = defaultUserSettings;

export type LayoutProps = {
    children: React.ReactNode;
};

export default function Layout({ children }: LayoutProps): JSX.Element {
    return (
        <div className='w-full h-screen bg-black overflow-hidden '>
            <Head>
                <title>{portfolioTitle || `${name}'s Portfolio`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className='w-full h-screen flex flex-wrap flex-row justify-center items-start overflow-y-auto'>
                <div className='w-full h-auto'><NavBar /></div>
                <div className='w-full h-auto'>{children}</div>
                <div className='w-full h-auto self-end'><Footer /></div>
            </section>
        </div>
    );
}
